// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportXExame.Config;

namespace SportXExame.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220131000358_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("SportXExame.Model.Cliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("cep")
                        .HasColumnType("longtext")
                        .HasColumnName("CEP");

                    b.Property<string>("classificacao")
                        .HasColumnType("longtext")
                        .HasColumnName("Classificacao");

                    b.Property<string>("cpfCNPJ")
                        .HasColumnType("longtext")
                        .HasColumnName("CPF/CNPJ");

                    b.Property<string>("email")
                        .HasColumnType("longtext")
                        .HasColumnName("Email");

                    b.Property<string>("nome")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nome");

                    b.HasKey("id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("SportXExame.Model.Telefone", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("telefone")
                        .HasColumnType("longtext")
                        .HasColumnName("Telefones");

                    b.HasKey("id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Telefone");
                });

            modelBuilder.Entity("SportXExame.Model.Telefone", b =>
                {
                    b.HasOne("SportXExame.Model.Cliente", "Cliente")
                        .WithMany("telefones")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("SportXExame.Model.Cliente", b =>
                {
                    b.Navigation("telefones");
                });
#pragma warning restore 612, 618
        }
    }
}
